import os

print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite')
input()
os.system('clear')
print("Whad do dentits call a astronaut's cavity?")
input()
print('A black hole!')
input()
os.system('clear')
print('Knock knock.')
input()
print("Who's there?")
input()
print("Interrupting cow.")
input()
print('Interrupting cow wh', end='')
print("MOOOOOOOOOO!")